kind: Deployment
apiVersion: apps/v1
metadata:
  name: coreapi-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: coreapi
  template:
    metadata:
      labels:
        app: coreapi
    spec:
      containers:
      - name: coreapi-pod
        image: alemoracr.azurecr.io/alemor/coreapi
        ports:
        - containerPort: 80
